databases:
  - name: urlshortenerdb
    plan: free
    databaseName: urlshortener
    user: urlshortener

services:
  - type: web
    plan: free
    name: urlshortener
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn url_shortener_project.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urlshortenerdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4